site_name: NFDI Small Disiplines
nav:
  - Research Data:
      - NFDI4SD: index.md
      - Small Disciplines: concept/smalldisciplines-en.md
      - Research Data: concept/researchdata-en.md
      - Paratext: concept/metadata.md
  - NFDI4SD Services:
      - Portfolio of services: services/NFDIservices.md
      - Computational Notebooks: services/bench.md
      - Publication: services/publication.md
      - Content Partner: services/contentprovider.md
  - Research Organisation:
      - Objectives and Task Areas: research/ObjectiveTask.md
      - Measures and Workpackages: research/means.md
      - User : research/integration.md
      - Epistemology: research/epistemology.md
  - Use Cases:
      Taxonomy: usecases/orientation.md
      Rock Art: usecases/rockart.md
      Ancient Sundials: usecases/sundials.md
      Karman Collection: usecases/karman.md
      Sinology: usecases/sinology.md
      Codex Florentinus: usecases/florentinus.md
      Euler Edition: usecases/leo.md
      Kepler: usecases/kepler.md
      Francis Drake: usecases/sirdrake.md
      Epidemology: usecases/bernoulli.md
      Exoplanets: usecases/exoplanets.md
  - Governance:
      - bodies: governance/bodies.md
      - bibliography: governance/biblio.md
  -  Impressum:
      impressum: impressum.md
theme:
  name: material
  custom_dir: overrides  
  font:
    text: Roboto
  language: en
  palette:
    scheme: netfrei  
  features:
    tabs: True
  custom_checkbox: True
  clickable_checkbox: True
  palette:
    primary: teal
    accent: "deep orange"
markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_blockdiag:
      format: svg
extra:
    social:
        - icon: material/home
          link: http://grasshoff.github.io/Cube/
plugins:
  - search
  - mknotebooks
  - bibtex:
      bib_file:  "NFDI.bib"
      cite_style:  "pandoc"
      csl_file: "chicago.csl"